name: workflow_02
on: 
  repository_dispatch:
    types: [update-package]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v4
